### ISSUE TITLE
Chapter 2.2.3, exercise 7: stack overflow on very long linked lists

### ISSUE THREAD

**Issue by masak** [masak/taocp-invert-linked-list#1]
I wrote this test:

```typescript
test('reversing a very long list does not cause a stack overflow', (t): void => {
    const LENGTH = 10_000;
    let longAscendingArray = Array.from({ length: LENGTH }, (x, i) => i);
    let input = makeLinkedList(...longAscendingArray);
    let longDescendingArray = Array.from({ length: LENGTH }, (x, i) => LENGTH - i - 1);
    let expectedOutput = makeLinkedList(...longDescendingArray);
    t.deepEqual(reverseLinkedList(input), expectedOutput);
});
```

Node fails with `Maximum call stack size exceeded`.

Iterative solutions are often equivalent to their recursive solutions, but this is one case where they're not. Ten thousand elements is a lot for a linked list, but it's not _too much_. A solution with just a loop wouldn't have this problem.

There's more about recursion limits in browsers [here](https://stackoverflow.com/questions/2805172/what-are-the-js-recursion-limits-for-firefox-chrome-safari-ie-etc); the exact numbers don't matter so much &mdash; what matters is that there are linked lists that are longer than those numbers.

**Comment by masak** [comment]
Read [this StackOverflow thread](https://stackoverflow.com/questions/35535312/stack-overflow-with-unique-ptr-linked-list), it's fascinating. It's about C++, and the situation when the stack overflow occurs is different; they're not reversing the list, only reclaiming its memory.

But it shows the danger of recursive algorithms in general &mdash; with big enough data structures, you will run out of stack. I'm pleased with the fact that you feel so comfortable with recursion that it ends up being your go-to solution... but as we can see in this issue, the complexity that we hand off to the call stack comes back as a _resource_ that can be depleted, and that's a design issue we need to take into consideration.

The issue becomes a little bit different if we can leverage tail-call optimization (so we don't consume any stack), but... (a) JavaScript implementations in general do not implement TCO, and (b) I believe a loop here can be just as clear and short, so why prefer the recursive version?

**Comment by claes-magnus** [comment]
Concerning recursion: the reason is simple (for me).

* I tried with recursion because only lately I'm beginning to be quite convenient with them. Therefore - to me - it's a end in it self, regardless the context (or rather, if it's for 'play' only), to write iterations with recursion, just for the practice! 

* Why do I use const? Because my view is that const is - even though I'm aware of the issues, i.e. it's not really constant (only for nums and strings) - an industry standard. Also, with const all over the place and lets reserverved for mutabillity I can easily see where I, in theory, could do better. This is naturally related  to me trying to get some grip of functional programming.

* In general: if performance is your end goal I've been taught, or that's what I *think* I've been taught ;), that non-recursive solutions often have much better performance. I must also confess I'm more fluent - fluent i relation to my 'level' - with for and while-looping. So why use them? ;) :)

* However, in this case my solution would've been easy to implement with a for-loop. The problem is rather, as you've stated in a mail, the 'complexity'... Unfortunately, I'm far from being able to produce a solution that match the 'simplicity' and 'elegance' of yours (in the issue).

**Comment by masak** [comment]
No worries, one step at a time. 🙂 I was trying to show with this issue that a recursive solution is _worse_ for some realistic use cases where an iterative solution is fine.

* Getting practice with recursive solutions is completely fine, of course. Treat this as an opportunity to learn in practice where an iterative solution differs from (and excels over) a recursive one.

* I didn't mention/question your use of `const`. I agree your view is industry standard, and I don't wish to spend time right now talking about the merits of `const` over `let`, if that's OK. It's a distraction from the main issue.

* Dunno about "much better" performance, but yes, calling and returning does have a non-zero performance overhead. I'm not keen on the "why use them" question (if I understand it correctly) about rejecting a method that you already master and that would have been sufficient/fitting. Good design (and level-3 thinking) is about picking the weakest tool in one's toolbox that does the job. Programming is already challenging enough.

* Is there a way we can collaborate on a `for` loop solution? Maybe using a Google Docs document? (I sent an invite.) Or, if you prefer to muddle through yourself, that's OK too.
